//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\shr\Desktop\Code\ClepsOfficialRepo\Cleps\Windows\ClepsToolset\ClepsToolset\ClepsParser\AntlrBuild\Cleps.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IClepsListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class ClepsBaseListener : IClepsListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.operatorSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorSymbol([NotNull] ClepsParser.OperatorSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.operatorSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorSymbol([NotNull] ClepsParser.OperatorSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.stringValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringValue([NotNull] ClepsParser.StringValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.stringValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringValue([NotNull] ClepsParser.StringValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] ClepsParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] ClepsParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.nestedIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedIdentifier([NotNull] ClepsParser.NestedIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.nestedIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedIdentifier([NotNull] ClepsParser.NestedIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.numeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumeric([NotNull] ClepsParser.NumericContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.numeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumeric([NotNull] ClepsParser.NumericContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classOrMemberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrMemberName([NotNull] ClepsParser.ClassOrMemberNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classOrMemberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrMemberName([NotNull] ClepsParser.ClassOrMemberNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.visibilityModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibilityModifier([NotNull] ClepsParser.VisibilityModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.visibilityModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibilityModifier([NotNull] ClepsParser.VisibilityModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.ArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] ClepsParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.ArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] ClepsParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.BasicType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicType([NotNull] ClepsParser.BasicTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.BasicType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicType([NotNull] ClepsParser.BasicTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.FunctionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionType([NotNull] ClepsParser.FunctionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.FunctionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionType([NotNull] ClepsParser.FunctionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.PointerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointerType([NotNull] ClepsParser.PointerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.PointerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointerType([NotNull] ClepsParser.PointerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.typenameAndVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypenameAndVoid([NotNull] ClepsParser.TypenameAndVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.typenameAndVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypenameAndVoid([NotNull] ClepsParser.TypenameAndVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] ClepsParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] ClepsParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.namespaceBlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceBlockStatement([NotNull] ClepsParser.NamespaceBlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.namespaceBlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceBlockStatement([NotNull] ClepsParser.NamespaceBlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.usingNamespaceStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingNamespaceStatement([NotNull] ClepsParser.UsingNamespaceStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.usingNamespaceStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingNamespaceStatement([NotNull] ClepsParser.UsingNamespaceStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.usingNamespaceStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingNamespaceStatements([NotNull] ClepsParser.UsingNamespaceStatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.usingNamespaceStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingNamespaceStatements([NotNull] ClepsParser.UsingNamespaceStatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classDeclarationStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclarationStatements([NotNull] ClepsParser.ClassDeclarationStatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classDeclarationStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclarationStatements([NotNull] ClepsParser.ClassDeclarationStatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classBodyStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBodyStatements([NotNull] ClepsParser.ClassBodyStatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classBodyStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBodyStatements([NotNull] ClepsParser.ClassBodyStatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.memberDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDeclarationStatement([NotNull] ClepsParser.MemberDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.memberDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDeclarationStatement([NotNull] ClepsParser.MemberDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.BinaryOperatorOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryOperatorOnExpression([NotNull] ClepsParser.BinaryOperatorOnExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.BinaryOperatorOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryOperatorOnExpression([NotNull] ClepsParser.BinaryOperatorOnExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.PreOperatorOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreOperatorOnExpression([NotNull] ClepsParser.PreOperatorOnExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.PreOperatorOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreOperatorOnExpression([NotNull] ClepsParser.PreOperatorOnExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.BracketedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracketedExpression([NotNull] ClepsParser.BracketedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.BracketedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracketedExpression([NotNull] ClepsParser.BracketedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.ArrayAccessOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccessOnExpression([NotNull] ClepsParser.ArrayAccessOnExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.ArrayAccessOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccessOnExpression([NotNull] ClepsParser.ArrayAccessOnExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.FieldAccessOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldAccessOnExpression([NotNull] ClepsParser.FieldAccessOnExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.FieldAccessOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldAccessOnExpression([NotNull] ClepsParser.FieldAccessOnExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.FunctionCallOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallOnExpression([NotNull] ClepsParser.FunctionCallOnExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.FunctionCallOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallOnExpression([NotNull] ClepsParser.FunctionCallOnExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.PostOperatorOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostOperatorOnExpression([NotNull] ClepsParser.PostOperatorOnExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.PostOperatorOnExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostOperatorOnExpression([NotNull] ClepsParser.PostOperatorOnExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.SimpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleExpression([NotNull] ClepsParser.SimpleExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.SimpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleExpression([NotNull] ClepsParser.SimpleExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.rightHandExpressionSimple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRightHandExpressionSimple([NotNull] ClepsParser.RightHandExpressionSimpleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.rightHandExpressionSimple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRightHandExpressionSimple([NotNull] ClepsParser.RightHandExpressionSimpleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.numericAssignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericAssignments([NotNull] ClepsParser.NumericAssignmentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.numericAssignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericAssignments([NotNull] ClepsParser.NumericAssignmentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.nullAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullAssignment([NotNull] ClepsParser.NullAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.nullAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullAssignment([NotNull] ClepsParser.NullAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.booleanAssignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanAssignments([NotNull] ClepsParser.BooleanAssignmentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.booleanAssignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanAssignments([NotNull] ClepsParser.BooleanAssignmentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.stringAssignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringAssignments([NotNull] ClepsParser.StringAssignmentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.stringAssignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringAssignments([NotNull] ClepsParser.StringAssignmentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.arrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAssignment([NotNull] ClepsParser.ArrayAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.arrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAssignment([NotNull] ClepsParser.ArrayAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionCallAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallAssignment([NotNull] ClepsParser.FunctionCallAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionCallAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallAssignment([NotNull] ClepsParser.FunctionCallAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableAssignment([NotNull] ClepsParser.VariableAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableAssignment([NotNull] ClepsParser.VariableAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.fieldOrClassAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOrClassAssignment([NotNull] ClepsParser.FieldOrClassAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.fieldOrClassAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOrClassAssignment([NotNull] ClepsParser.FieldOrClassAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classInstanceAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassInstanceAssignment([NotNull] ClepsParser.ClassInstanceAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classInstanceAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassInstanceAssignment([NotNull] ClepsParser.ClassInstanceAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionAssignment([NotNull] ClepsParser.FunctionAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionAssignment([NotNull] ClepsParser.FunctionAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] ClepsParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] ClepsParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementBlock([NotNull] ClepsParser.StatementBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.statementBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementBlock([NotNull] ClepsParser.StatementBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionStatement([NotNull] ClepsParser.FunctionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionStatement([NotNull] ClepsParser.FunctionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionReturnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionReturnStatement([NotNull] ClepsParser.FunctionReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionReturnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionReturnStatement([NotNull] ClepsParser.FunctionReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionVariableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionVariableDeclarationStatement([NotNull] ClepsParser.FunctionVariableDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionVariableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionVariableDeclarationStatement([NotNull] ClepsParser.FunctionVariableDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionVariableAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionVariableAssignmentStatement([NotNull] ClepsParser.FunctionVariableAssignmentStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionVariableAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionVariableAssignmentStatement([NotNull] ClepsParser.FunctionVariableAssignmentStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionFieldAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionFieldAssignmentStatement([NotNull] ClepsParser.FunctionFieldAssignmentStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionFieldAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionFieldAssignmentStatement([NotNull] ClepsParser.FunctionFieldAssignmentStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionArrayAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionArrayAssignmentStatement([NotNull] ClepsParser.FunctionArrayAssignmentStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionArrayAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionArrayAssignmentStatement([NotNull] ClepsParser.FunctionArrayAssignmentStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionCallStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallStatement([NotNull] ClepsParser.FunctionCallStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionCallStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallStatement([NotNull] ClepsParser.FunctionCallStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] ClepsParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] ClepsParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.doWhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileStatement([NotNull] ClepsParser.DoWhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.doWhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileStatement([NotNull] ClepsParser.DoWhileStatementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
