//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\shr\Desktop\Code\ClepsOfficialRepo\Cleps\Windows\ClepsToolset\ClepsToolset\ClepsParser\AntlrBuild\Cleps.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ClepsParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IClepsVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorSymbol([NotNull] ClepsParser.OperatorSymbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringValue([NotNull] ClepsParser.StringValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] ClepsParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.nestedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedIdentifier([NotNull] ClepsParser.NestedIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric([NotNull] ClepsParser.NumericContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.classOrMemberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOrMemberName([NotNull] ClepsParser.ClassOrMemberNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.visibilityModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibilityModifier([NotNull] ClepsParser.VisibilityModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayType([NotNull] ClepsParser.ArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BasicType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicType([NotNull] ClepsParser.BasicTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionType([NotNull] ClepsParser.FunctionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PointerType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerType([NotNull] ClepsParser.PointerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.typenameAndVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypenameAndVoid([NotNull] ClepsParser.TypenameAndVoidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] ClepsParser.CompilationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.namespaceBlockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceBlockStatement([NotNull] ClepsParser.NamespaceBlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.usingNamespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingNamespaceStatement([NotNull] ClepsParser.UsingNamespaceStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.usingNamespaceStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingNamespaceStatements([NotNull] ClepsParser.UsingNamespaceStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.classDeclarationStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclarationStatements([NotNull] ClepsParser.ClassDeclarationStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.classBodyStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBodyStatements([NotNull] ClepsParser.ClassBodyStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.memberDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclarationStatement([NotNull] ClepsParser.MemberDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOperatorOnExpression([NotNull] ClepsParser.BinaryOperatorOnExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreOperatorOnExpression([NotNull] ClepsParser.PreOperatorOnExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BracketedExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracketedExpression([NotNull] ClepsParser.BracketedExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayAccessOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccessOnExpression([NotNull] ClepsParser.ArrayAccessOnExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FieldAccessOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccessOnExpression([NotNull] ClepsParser.FieldAccessOnExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionCallOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallOnExpression([NotNull] ClepsParser.FunctionCallOnExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostOperatorOnExpression([NotNull] ClepsParser.PostOperatorOnExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SimpleExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleExpression([NotNull] ClepsParser.SimpleExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.rightHandExpressionSimple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRightHandExpressionSimple([NotNull] ClepsParser.RightHandExpressionSimpleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.numericAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericAssignments([NotNull] ClepsParser.NumericAssignmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.nullAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullAssignment([NotNull] ClepsParser.NullAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.booleanAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanAssignments([NotNull] ClepsParser.BooleanAssignmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.stringAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringAssignments([NotNull] ClepsParser.StringAssignmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.arrayAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignment([NotNull] ClepsParser.ArrayAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionCallAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallAssignment([NotNull] ClepsParser.FunctionCallAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignment([NotNull] ClepsParser.VariableAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.fieldOrClassAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOrClassAssignment([NotNull] ClepsParser.FieldOrClassAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.classInstanceAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInstanceAssignment([NotNull] ClepsParser.ClassInstanceAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionAssignment([NotNull] ClepsParser.FunctionAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.platformAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlatformAssignment([NotNull] ClepsParser.PlatformAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] ClepsParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementBlock([NotNull] ClepsParser.StatementBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionStatement([NotNull] ClepsParser.FunctionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionReturnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionReturnStatement([NotNull] ClepsParser.FunctionReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionVariableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVariableDeclarationStatement([NotNull] ClepsParser.FunctionVariableDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionVariableAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVariableAssignmentStatement([NotNull] ClepsParser.FunctionVariableAssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionFieldAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionFieldAssignmentStatement([NotNull] ClepsParser.FunctionFieldAssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionArrayAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionArrayAssignmentStatement([NotNull] ClepsParser.FunctionArrayAssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.functionCallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallStatement([NotNull] ClepsParser.FunctionCallStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] ClepsParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileStatement([NotNull] ClepsParser.DoWhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.nativeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeStatement([NotNull] ClepsParser.NativeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ClepsParser.nativeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeCode([NotNull] ClepsParser.NativeCodeContext context);
}
