//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\shr\Desktop\Code\ClepsOfficialRepo\Cleps\Windows\ClepsToolset\ClepsToolset\ClepsParser\AntlrBuild\Cleps.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ClepsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IClepsListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorSymbol([NotNull] ClepsParser.OperatorSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorSymbol([NotNull] ClepsParser.OperatorSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringValue([NotNull] ClepsParser.StringValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringValue([NotNull] ClepsParser.StringValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] ClepsParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] ClepsParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.nestedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedIdentifier([NotNull] ClepsParser.NestedIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.nestedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedIdentifier([NotNull] ClepsParser.NestedIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumeric([NotNull] ClepsParser.NumericContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumeric([NotNull] ClepsParser.NumericContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classOrMemberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrMemberName([NotNull] ClepsParser.ClassOrMemberNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classOrMemberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrMemberName([NotNull] ClepsParser.ClassOrMemberNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.visibilityModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibilityModifier([NotNull] ClepsParser.VisibilityModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.visibilityModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibilityModifier([NotNull] ClepsParser.VisibilityModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayType([NotNull] ClepsParser.ArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayType([NotNull] ClepsParser.ArrayTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BasicType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicType([NotNull] ClepsParser.BasicTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BasicType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicType([NotNull] ClepsParser.BasicTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionType([NotNull] ClepsParser.FunctionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionType([NotNull] ClepsParser.FunctionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PointerType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerType([NotNull] ClepsParser.PointerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PointerType</c>
	/// labeled alternative in <see cref="ClepsParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerType([NotNull] ClepsParser.PointerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.typenameAndVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypenameAndVoid([NotNull] ClepsParser.TypenameAndVoidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.typenameAndVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypenameAndVoid([NotNull] ClepsParser.TypenameAndVoidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] ClepsParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] ClepsParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.namespaceBlockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceBlockStatement([NotNull] ClepsParser.NamespaceBlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.namespaceBlockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceBlockStatement([NotNull] ClepsParser.NamespaceBlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.usingNamespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingNamespaceStatement([NotNull] ClepsParser.UsingNamespaceStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.usingNamespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingNamespaceStatement([NotNull] ClepsParser.UsingNamespaceStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.usingNamespaceStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingNamespaceStatements([NotNull] ClepsParser.UsingNamespaceStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.usingNamespaceStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingNamespaceStatements([NotNull] ClepsParser.UsingNamespaceStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classDeclarationStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclarationStatements([NotNull] ClepsParser.ClassDeclarationStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classDeclarationStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclarationStatements([NotNull] ClepsParser.ClassDeclarationStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classBodyStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBodyStatements([NotNull] ClepsParser.ClassBodyStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classBodyStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBodyStatements([NotNull] ClepsParser.ClassBodyStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.memberDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclarationStatement([NotNull] ClepsParser.MemberDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.memberDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclarationStatement([NotNull] ClepsParser.MemberDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOperatorOnExpression([NotNull] ClepsParser.BinaryOperatorOnExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOperatorOnExpression([NotNull] ClepsParser.BinaryOperatorOnExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreOperatorOnExpression([NotNull] ClepsParser.PreOperatorOnExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreOperatorOnExpression([NotNull] ClepsParser.PreOperatorOnExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BracketedExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracketedExpression([NotNull] ClepsParser.BracketedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BracketedExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracketedExpression([NotNull] ClepsParser.BracketedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccessOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccessOnExpression([NotNull] ClepsParser.ArrayAccessOnExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccessOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccessOnExpression([NotNull] ClepsParser.ArrayAccessOnExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FieldAccessOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldAccessOnExpression([NotNull] ClepsParser.FieldAccessOnExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FieldAccessOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldAccessOnExpression([NotNull] ClepsParser.FieldAccessOnExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionCallOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallOnExpression([NotNull] ClepsParser.FunctionCallOnExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionCallOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallOnExpression([NotNull] ClepsParser.FunctionCallOnExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostOperatorOnExpression([NotNull] ClepsParser.PostOperatorOnExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostOperatorOnExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostOperatorOnExpression([NotNull] ClepsParser.PostOperatorOnExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleExpression([NotNull] ClepsParser.SimpleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleExpression</c>
	/// labeled alternative in <see cref="ClepsParser.rightHandExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleExpression([NotNull] ClepsParser.SimpleExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.rightHandExpressionSimple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRightHandExpressionSimple([NotNull] ClepsParser.RightHandExpressionSimpleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.rightHandExpressionSimple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRightHandExpressionSimple([NotNull] ClepsParser.RightHandExpressionSimpleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.numericAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericAssignments([NotNull] ClepsParser.NumericAssignmentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.numericAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericAssignments([NotNull] ClepsParser.NumericAssignmentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.nullAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullAssignment([NotNull] ClepsParser.NullAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.nullAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullAssignment([NotNull] ClepsParser.NullAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.booleanAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanAssignments([NotNull] ClepsParser.BooleanAssignmentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.booleanAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanAssignments([NotNull] ClepsParser.BooleanAssignmentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.stringAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringAssignments([NotNull] ClepsParser.StringAssignmentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.stringAssignments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringAssignments([NotNull] ClepsParser.StringAssignmentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.arrayAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAssignment([NotNull] ClepsParser.ArrayAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.arrayAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAssignment([NotNull] ClepsParser.ArrayAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionCallAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallAssignment([NotNull] ClepsParser.FunctionCallAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionCallAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallAssignment([NotNull] ClepsParser.FunctionCallAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableAssignment([NotNull] ClepsParser.VariableAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableAssignment([NotNull] ClepsParser.VariableAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.fieldOrClassAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOrClassAssignment([NotNull] ClepsParser.FieldOrClassAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.fieldOrClassAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOrClassAssignment([NotNull] ClepsParser.FieldOrClassAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.classInstanceAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassInstanceAssignment([NotNull] ClepsParser.ClassInstanceAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.classInstanceAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassInstanceAssignment([NotNull] ClepsParser.ClassInstanceAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionAssignment([NotNull] ClepsParser.FunctionAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionAssignment([NotNull] ClepsParser.FunctionAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.platformAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlatformAssignment([NotNull] ClepsParser.PlatformAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.platformAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlatformAssignment([NotNull] ClepsParser.PlatformAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] ClepsParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] ClepsParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementBlock([NotNull] ClepsParser.StatementBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementBlock([NotNull] ClepsParser.StatementBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionStatement([NotNull] ClepsParser.FunctionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionStatement([NotNull] ClepsParser.FunctionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionReturnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionReturnStatement([NotNull] ClepsParser.FunctionReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionReturnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionReturnStatement([NotNull] ClepsParser.FunctionReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionVariableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionVariableDeclarationStatement([NotNull] ClepsParser.FunctionVariableDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionVariableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionVariableDeclarationStatement([NotNull] ClepsParser.FunctionVariableDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionVariableAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionVariableAssignmentStatement([NotNull] ClepsParser.FunctionVariableAssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionVariableAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionVariableAssignmentStatement([NotNull] ClepsParser.FunctionVariableAssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionFieldAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionFieldAssignmentStatement([NotNull] ClepsParser.FunctionFieldAssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionFieldAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionFieldAssignmentStatement([NotNull] ClepsParser.FunctionFieldAssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionArrayAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionArrayAssignmentStatement([NotNull] ClepsParser.FunctionArrayAssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionArrayAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionArrayAssignmentStatement([NotNull] ClepsParser.FunctionArrayAssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.functionCallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallStatement([NotNull] ClepsParser.FunctionCallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.functionCallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallStatement([NotNull] ClepsParser.FunctionCallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] ClepsParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] ClepsParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileStatement([NotNull] ClepsParser.DoWhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileStatement([NotNull] ClepsParser.DoWhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.nativeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNativeStatement([NotNull] ClepsParser.NativeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.nativeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNativeStatement([NotNull] ClepsParser.NativeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ClepsParser.nativeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNativeCode([NotNull] ClepsParser.NativeCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ClepsParser.nativeCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNativeCode([NotNull] ClepsParser.NativeCodeContext context);
}
